# Generated by Django 4.2.21 on 2025-06-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_category_alter_topic_category"),
    ]

    operations = []
