# Generated by Django 4.2.21 on 2025-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0003_auto_20250601_1249"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="category",
            field=models.CharField(max_length=100),
        ),
    ]
