# Generated by Django 4.2.21 on 2025-06-01 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0004_alter_topic_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="topics.category",
            ),
        ),
    ]
