# Generated by Django 4.2.21 on 2025-06-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0005_alter_topic_category"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
    ]
